#!/usr/bin/env python
import os, re
import json
from subprocess import check_call, CalledProcessError

# get some information about the test
modelname = raw_input("modelname=")
path = raw_input("path=")
directory = path

# from here on out, we will be in the test's directory
here = os.getcwd()
os.chdir(directory)

#=========================================================
# now, we check that the
# 1. executable builds
#==========================================================
title = "Build model"
critical = True
passed = True
msg = ""
warn = ""

def fail(reason):
    global msg, passed
    passed = False
    msg += reason+"\n"

try:
    check_call("make")
except CalledProcessError as e:
    fail("Could not build: %r" % e)

os.chdir(here)
results = {
    "property-id": "tag:staff@noreply.openkim.org,2014-08-05:property/verification-check",
    "passed": passed,
    "message": msg,
    "warning": warn,
    "critical": critical,
    "title": title
}

json.dump(
    [results], open("output/results.edn", "w"), 
    separators=(' ', ' '), indent=4
)
